### PR TITLE
Allow integer timestamps in DateTime::filter

### PR DESCRIPTION
**Pull request by chadicus**

### CODE REVIEW

**Comment by chrisryan** [comment]
What is some passes in 0 or a negative number?

**Comment by chadicus** [comment]
```php
ctype_digit('-1') === false
```
The behavior would be the same as it is now.

**Comment by chadicus** [comment]
A value of '0' would not throw any errors

```php
$input = 0;
if (ctype_digit($input)) { /// === true
    $input = "@{$input}";
}

$date =  new \DateTime($input);
echo $date->format('r');
// Outputs Thu, 01 Jan 1970 00:00:00 +0000
```

I don't know if we should consider 0 an error or not.

**Comment by nubs** [comment]
Generally `0` is perfectly fine for a timestamp.  Why make it special but not `1`?  They are only one second apart :)

**Pull request merged**
