### PR TITLE
Allow callable as haystack in Arrays::in

### PR DESCRIPTION
**Pull request by chadicus**

### CODE REVIEW

**Comment by nubs** [comment]
why not just call the haystack function before passing it to here?  e.g., `Arrays::in('bar', $callable())` instead of `Arrays::in('bar', $callable)`?

**Comment by nubs** [comment]
Documentation could use an update too.

**Comment by chadicus** [comment]
Yeah, true, calling it just before would be fine, unless the callable was an API call or you wanted to pull the data at the last minute for some reason. But yes, this is probably not necessary.

**Comment by chadicus** [comment]
FYI, this came up because I'm working on a project where I need to store the filters in json

**Comment by nubs** [comment]
That could make sense :)

**Comment by chrisryan** [comment]
:+1:

**Pull request closed without merging**
